services:
  - type: web
    name: paka-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: ADMIN_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
